routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('test', function(){
	\Log::info('Log por Consola');
});

Route::resource('contacts','Contacts');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //MODELO DE CONTACTOS
    protected $fillable = [
        "user_id","name","email"
    ];

    //Relacion de pertenencia
    public function user(){
    	return $this->belongsTo('\App\User');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    function contacts(){
        return $this->hasMany('\App\Contact');
    }
}

app/Http/Controllers/Contacts.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Contact;
use Storage;
use Session;

class Contacts extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $objContact= new \App\Contact();
        $user= \Auth::user();
        $data=$user->contacts->get->all();
        dd($data);
        return view('home')->with('contacts',$data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $arrData = array('name' =>'',
             'email'=>'',
             'file'=>'',
             'id'=>'',
             'title'=>'Crear Contacto',
             'route'=>'contacts/');
        Session::forget('msj');
        Session::forget('nomsj');
        //dd($arrData);
        return view('contacts.create')->with(['contact'=>$arrData]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function saveImg($img){;
        $name_file=(time().'_'.str_replace(' ', '_', $img->getClientOriginalName()));
        if(\Storage::disk('imgContacts')->put($name_file,\File::get($img))){
            return $name_file;
        }else{
            false;
        }
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
            'email'=>'required|email'
            //,'contactfile'=>'required'
            ]);

        //llamada a Objetos
        $user            =\Auth::user();
        $contacts        =new \App\Contact();
        
        //carga de valores
        $contacts->name  =$request->name;
        $contacts->email =$request->email;

        if(!empty($request->contactfile)){
            $img=$request->contactfile;
            $nameFile=$this->saveImg($img);
            if($nameFile!=false){
                $contacts->file=$nameFile;
            }
        }
        if ($user->contacts()->save($contacts)->save()) {
            //Variable de Session
            return back()->with('msj','Datos Guardados con Exito');
        }else{
            return back()->with('nomsj','Error en la Base de Datos');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $objContact= new \App\Contact();
        $data=$objContact::find($id);
        $arrData = array('name' =>$data->name,
             'email'=>$data->email,
             'file'=>$data->file,
             'id'=>$data->id,
             'title'=>'Editar Contactos',
             'route'=>'contacts/');
        Session::forget('msj');
        Session::forget('nomsj');
        //dd($arrData);
        return view('contacts.create')->with(['contact'=>$arrData]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        dd($request);
        $objContact  = new \App\Contact();
        $data        =$objContact::find($id);
        $data->email =$request->email;
        $data->name  =$request->name;

        if (!empty($request->file)) {
            if(!empty($data->file)){
                $delete=$this->delete($id);
            }
            $nameImg=$this->saveImg($request->file);
            if($nameImg!=false){
                $data->file=$nameImg;
            }
        }
        if ($data->save()) {
            $arrData = array('name' =>$data->name,
                 'email'=>$data->email,
                 'file'=>$data->file,
                 'id'=>$data->id,
                 'title'=>'Editar Contactos',
                 'route'=>'contacts/');
        return view('create.contacts')->with(['contact'=>$arrData]);
        }else{
            return view('errors.503');
        }
    }



    public function deleteImg($id){
        $objContact= new \App\Contact();
        $data=$objContact::find($id);
        $img=$data->file;
        $delete=\Storage::disk('imgContacts')->delete($img);
        if($delete){
            $data->file=null;
            return $data->save();
        }else{
            return false;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Contact;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $objContact= new \App\Contact();
        $user=\Auth::user();
        $data=$user->contacts()->get()->all();
        //dd($data);
        return view('home')->with('contacts',$data);
    }
}

resources/views/contacts/create.blade.php
{{-- Informar a los Usuarios de los errores --}}

@if(!empty($errors))
  <ul>
    @foreach($errors->all() AS $error)
      <li>{{$error}}</li>
    @endforeach
  </ul>
@endif
{{--VALIDACIONES--}}
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
          <div class="panel-heading">{{$contact['title']}}}</div>
          <div class="panel-body">
            @if(session()->has('msj'))
            <div class="alert alert-success">{{session('msj')}}</div>
            @elseif(session()->has('nomsj'))
            <div class="alert alert-success">{{session('msj')}}</div>
            @endif

            <form role="form" action="{{url($contact['route'])}}" method="POST" enctype="multipart/form-data">
              <div class="form-group">
                <label for="name">Nombres</label>
                <input name="name" type="text" class="form-control" id="name" placeholder="Pedro Eduardo Perez" value="{{$contact['name']}}">
              </div>  

              <div class="form-group">
                <label for="email">Email</label>
                <input name="email" type="email" class="form-control" id="Email1" placeholder="pedroperez@ejemplo.com" value="{{$contact['email']}}">
              </div>
              @if($errors->has('name'))
              <span style="color:red">{{$errors->first('email')}}</span>
              @endif
              <div class="form-group">
                <label for="contactfile">Archivo</label>
                <input name="contactfile" type="file" id="contactfile">
                <p class="help-block">Puede subir su imagen aqui.</p>
              </div>
              @if(!empty($contact['file']))
                <div style="align-content:center">
                  <img src="{{url('imgContacts/'.$contact['file'])}}" alt="">
                </div>
              @endif

              @if(!empty($contact['id']))
                <input type="hidden" name="_method" value="PUT">
              @endif

              <button type="submit" class="btn btn-default">Enviar</button>
              {{csrf_field()}}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/contacts/index.blade.php
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Email</th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      @if(!empty($contacts))
        @foreach($contacts as $cont)
          <tr>
            <td>{{$cont->name}}</td>
            <td>{{$cont->email}}</td>
            <td>
              <a href="contacts/{{$cont->id}}/edit">Editar</a>
              <a href="{{route('contacts.destroy',array($cont->id)) }}" data-method="delete" rel="nofollow" data-confirm="Desea Eliminar?">Eliminar</a>
            </td>
          </tr>
        @endforeach
      @else
        <td colspan="3">No hay contactos que mostrar</td>
      @endif

    </tbody>
  </table>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Inicio</div>

                <div class="panel-body">
                   @include('contacts.index')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <li><a href="{{url('contacts/create')}}">Crear Contactos</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>